"""empty message

Revision ID: 891a2bf86b34
Revises: 18bbbfa075a4
Create Date: 2021-06-03 14:56:40.055460

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "891a2bf86b34"
down_revision = "18bbbfa075a4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_invitations",
        sa.Column("id", sa.INTEGER(), nullable=False, comment="Unique row identifier"),
        sa.Column(
            "cancelled_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="timestamp for cancellation of record",
        ),
        sa.Column("name", sa.String(), nullable=False, comment="user's name"),
        sa.Column(
            "email", sa.String(), nullable=True, comment="User's personal unique email"
        ),
        sa.Column("org_id", sa.Integer(), nullable=True),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("position_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column(
            "date_added",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="row timestamp",
        ),
        sa.Column(
            "date_updated",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="timestamp for last updated",
        ),
        sa.Column("added_by_id", sa.INTEGER(), nullable=True),
        sa.Column(
            "updated_by_id", sa.INTEGER(), nullable=True, comment="fk for user's table"
        ),
        sa.Column(
            "cancelled_by_id",
            sa.INTEGER(),
            nullable=True,
            comment="fk for user's table",
        ),
        sa.ForeignKeyConstraint(
            ["added_by_id"],
            ["users.id"],
            name=op.f("fk_users_invitations_added_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by_id"],
            ["users.id"],
            name=op.f("fk_users_invitations_cancelled_by_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["organization_departments.id"],
            name=op.f("fk_users_invitations_department_id_organization_departments"),
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_users_invitations_org_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["users.id"],
            name=op.f("fk_users_invitations_updated_by_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users_invitations")),
        sa.UniqueConstraint("email", name=op.f("uq_users_invitations_email")),
    )
    op.alter_column(
        "organization_departments",
        "org_id",
        existing_type=sa.INTEGER(),
        comment="",
        existing_nullable=True,
    )
    op.alter_column(
        "organizations",
        "contact_email",
        existing_type=sa.VARCHAR(),
        comment="",
        existing_nullable=False,
    )
    op.alter_column(
        "organizations",
        "contact_phone",
        existing_type=sa.VARCHAR(),
        comment="",
        existing_nullable=False,
    )
    op.alter_column(
        "projects",
        "org_id",
        existing_type=sa.INTEGER(),
        comment="",
        existing_nullable=True,
    )
    op.alter_column(
        "user_affiliation",
        "user_id",
        existing_type=sa.INTEGER(),
        comment="",
        existing_nullable=False,
    )
    op.alter_column(
        "user_affiliation",
        "org_id",
        existing_type=sa.INTEGER(),
        comment="",
        existing_nullable=True,
    )
    op.alter_column(
        "user_affiliation",
        "department_id",
        existing_type=sa.INTEGER(),
        comment="",
        existing_nullable=True,
    )
    op.alter_column(
        "user_affiliation",
        "position_id",
        existing_type=sa.INTEGER(),
        comment="",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user_affiliation",
        "position_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="",
        existing_nullable=False,
    )
    op.alter_column(
        "user_affiliation",
        "department_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="",
        existing_nullable=True,
    )
    op.alter_column(
        "user_affiliation",
        "org_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="",
        existing_nullable=True,
    )
    op.alter_column(
        "user_affiliation",
        "user_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="",
        existing_nullable=False,
    )
    op.alter_column(
        "projects",
        "org_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="",
        existing_nullable=True,
    )
    op.alter_column(
        "organizations",
        "contact_phone",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="",
        existing_nullable=False,
    )
    op.alter_column(
        "organizations",
        "contact_email",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="",
        existing_nullable=False,
    )
    op.alter_column(
        "organization_departments",
        "org_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="",
        existing_nullable=True,
    )
    op.drop_table("users_invitations")
    # ### end Alembic commands ###
