"""empty message

Revision ID: d2067441f202
Revises: 5018177736d6
Create Date: 2021-05-31 14:27:38.471970

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d2067441f202"
down_revision = "5018177736d6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "organization_departments",
        "org_id",
        existing_type=sa.INTEGER(),
        comment="",
        existing_nullable=True,
    )
    op.alter_column(
        "organizations",
        "contact_email",
        existing_type=sa.VARCHAR(),
        comment="",
        existing_nullable=False,
    )
    op.alter_column(
        "organizations",
        "contact_phone",
        existing_type=sa.VARCHAR(),
        comment="",
        existing_nullable=False,
    )
    op.add_column(
        "users",
        sa.Column("phone", sa.String(), nullable=True, comment="Contact number"),
    )
    op.add_column(
        "users",
        sa.Column(
            "date_added",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="row timestamp",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "date_updated",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="timestamp for last updated",
        ),
    )
    op.add_column("users", sa.Column("added_by_id", sa.INTEGER(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "updated_by_id", sa.INTEGER(), nullable=True, comment="fk for user's table"
        ),
    )
    op.create_foreign_key(
        op.f("fk_users_updated_by_id_users"),
        "users",
        "users",
        ["updated_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_users_added_by_id_users"), "users", "users", ["added_by_id"], ["id"]
    )
    op.drop_column("users", "mobile")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "mobile",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Contact number",
        ),
    )
    op.drop_constraint(op.f("fk_users_added_by_id_users"), "users", type_="foreignkey")
    op.drop_constraint(
        op.f("fk_users_updated_by_id_users"), "users", type_="foreignkey"
    )
    op.drop_column("users", "updated_by_id")
    op.drop_column("users", "added_by_id")
    op.drop_column("users", "date_updated")
    op.drop_column("users", "date_added")
    op.drop_column("users", "phone")
    op.alter_column(
        "organizations",
        "contact_phone",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="",
        existing_nullable=False,
    )
    op.alter_column(
        "organizations",
        "contact_email",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="",
        existing_nullable=False,
    )
    op.alter_column(
        "organization_departments",
        "org_id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="",
        existing_nullable=True,
    )
    # ### end Alembic commands ###
