"""empty message

Revision ID: ec19284d4dbd
Revises: d88b673bf14d
Create Date: 2021-05-26 11:06:12.269384

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ec19284d4dbd"
down_revision = "d88b673bf14d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column(
            "is_public",
            sa.BOOLEAN(),
            server_default=sa.text("CAST(true AS BOOLEAN)"),
            nullable=False,
            comment="flags the project as public",
        ),
    )
    op.add_column(
        "projects",
        sa.Column("logo", sa.String(), nullable=True, comment="url to project's logo"),
    )
    op.alter_column(
        "projects",
        "start_date",
        existing_type=sa.DATE(),
        comment="project's start date",
        existing_comment="timestamp for project's start date",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "start_date",
        existing_type=sa.DATE(),
        comment="timestamp for project's start date",
        existing_comment="project's start date",
        existing_nullable=False,
    )
    op.drop_column("projects", "logo")
    op.drop_column("projects", "is_public")
    # ### end Alembic commands ###
